---
  - name: Prepare host name JSON templates
    template:
      src: templates/hostname.json.j2
      dest: ./hostname_{{ hostvars[inventory_hostname].inventory_hostname }}.json
    delegate_to: 127.0.0.1

  - name: Ensure hostnames are correct
    ops_template:
      host: localhost
      transport: rest
      validate_certs: False
      src: ./hostname_{{ hostvars[inventory_hostname].inventory_hostname }}.json
      username: root
      password:

  - name: Remove temporaly templates
    file:
      path: ./hostname_{{ hostvars[inventory_hostname].inventory_hostname }}.json
      state: absent
    delegate_to: 127.0.0.1
